GET http://localhost:5104/users

###
GET http://localhost:5104/users/7

###
POST http://localhost:5104/users/
Content-Type: application/json

{
    "name": "Gon"
}

###
PUT http://localhost:5104/users/7
Content-Type: application/json

{
    "name": "Gokmk"
}

###
DELETE http://localhost:5104/users/9